# Generated by Django 2.2.4 on 2019-10-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='student',
            field=models.ManyToManyField(to='students.Students'),
        ),
    ]
