# Generated by Django 2.2.4 on 2019-10-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjects_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='student',
            field=models.ManyToManyField(related_name='first_name', to='students.Students'),
        ),
    ]
