# Generated by Django 2.2.4 on 2019-10-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20191019_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='student',
        ),
    ]
